language: node_js
node_js: node
services:
     - mongodb
deploy:
  provider: heroku
  api_key:
    secure: yo5vXQC5r5C8Q6mRVGbnKfXiZcOTSMB5LSbyPdIvOIJFwzn19/H2va8vg7UZjpgWfY+8judTBNo3/Ea7pzSPJFUACtMdRedKiaDNDj9y1evet7zUYqphGwWSP1CGICfZ/vN3GYqoog920gyrzmebBPm7DeU/ATVPGSXWn3Kz6flG5tI6uDfOKrODT/BtIcBH+uWWcAVoFnXICBXedFRJ6dxUJLHEIxYXX5ZagUbeN2qQ09dz1NjqgrygAKw2DNV8DNMzafT+tt+ddy+vCPE12e/Pjwsmwv/HSldHSe+t0pl82GR/tAR0h8bcYz91/6VUS1G901D31puSeVtydE6fGcrNtZ1i+3vogAMBaycGMuaA+jCH0yKWTi+gF/UNO9HOvt8H30ocpVRFCgxULCky44aNATTvRUsXW9D6pqTXAdT9ef1nPBa0YL5zbTgzKRENzuBmqsH6F698ObCnLRqlN6IdAtKT2CO7W5jqY+k/I0pUzvbU6cEaSJOURbjadJ//gQUaA0AE0k4Hx/puA1+DZ8HDcZletqlAcG1KjYfAKEbkAYB2dZFCPtKZx1DtOHF0GgIBnX5yu5P3fy6NgosrCHf1C7n+vGNigSRBiuV2LYzGe/ukFAWUYVBYLflU3TxNAsHyySuhUvcn/ZmYOzjMY/hTdRlD53mguy+KsRNtXTA=
  app: dry-thicket-11732
  on:
    repo: raysmithdev/full-stack-app-client-api
